"""align_user_status_default_to_pending

Revision ID: 063c551526f6
Revises: 765cbcbcb6b1
Create Date: 2026-06-26 19:02:33.482523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '063c551526f6'
down_revision: Union[str, Sequence[str], None] = '765cbcbcb6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', name='userstatus'),
               server_default='PENDING',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', name='userstatus'),
               server_default=sa.text("'ACTIVE'::userstatus"),
               existing_nullable=False)
    # ### end Alembic commands ###
