"""add organization_id to projects

Revision ID: 2049016dfeb5
Revises: 9baa2824fbd2
Create Date: 2026-06-18 02:49:29.888330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2049016dfeb5'
down_revision: Union[str, Sequence[str], None] = '9baa2824fbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###

    # --- START CUSTOM DATA MIGRATION ---
    connection = op.get_bind()

    # 1. Select all users
    users = connection.execute(sa.text("SELECT id, name FROM users")).fetchall()

    for user in users:
        # 2. Create Personal Workspace for each user
        org_name = f"Personal Workspace - {user.name}" if user.name else f"Personal Workspace - User {user.id}"
        org_result = connection.execute(
            sa.text("INSERT INTO organizations (name) VALUES (:name) RETURNING id"),
            {"name": org_name}
        )
        org_id = org_result.scalar()

        # 3. Bind user to the organization as OWNER
        connection.execute(
            sa.text(
                "INSERT INTO organization_members (user_id, organization_id, role) "
                "VALUES (:user_id, :organization_id, 'OWNER')"
            ),
            {"user_id": user.id, "organization_id": org_id}
        )

        # 4. Migrate projects to this new organization
        connection.execute(
            sa.text("UPDATE projects SET organization_id = :org_id WHERE owner_id = :user_id"),
            {"org_id": org_id, "user_id": user.id}
        )
        
    # 5. Make organization_id non-nullable
    op.alter_column('projects', 'organization_id', nullable=False)
    # --- END CUSTOM DATA MIGRATION ---


def downgrade() -> None:
    """Downgrade schema."""
    # --- START CUSTOM ROLLBACK ---
    op.alter_column('projects', 'organization_id', nullable=True)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE projects SET organization_id = NULL"))
    connection.execute(sa.text("DELETE FROM organization_members"))
    connection.execute(sa.text("DELETE FROM organizations"))
    # --- END CUSTOM ROLLBACK ---

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'organization_id')
    # ### end Alembic commands ###
