"""add organization invites

Revision ID: dd693df4ca35
Revises: 2049016dfeb5
Create Date: 2026-06-18 17:45:00.553398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'dd693df4ca35'
down_revision: Union[str, Sequence[str], None] = '2049016dfeb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', name='organizationrole', create_type=False), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invites_email'), 'organization_invites', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invites_id'), 'organization_invites', ['id'], unique=False)
    op.create_index(op.f('ix_organization_invites_token'), 'organization_invites', ['token'], unique=True)
    op.create_index('ix_unique_pending_invite', 'organization_invites', ['organization_id', 'email'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_pending_invite', table_name='organization_invites', if_exists=True)
    op.drop_index(op.f('ix_organization_invites_token'), table_name='organization_invites')
    op.drop_index(op.f('ix_organization_invites_id'), table_name='organization_invites')
    op.drop_index(op.f('ix_organization_invites_email'), table_name='organization_invites')
    op.drop_table('organization_invites')
    op.execute("DROP TYPE invitestatus")
