"""add_telegram_message_id_to_users

Revision ID: fee4994d5308
Revises: d7fa615cd804
Create Date: 2026-07-07 23:46:38.889267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee4994d5308'
down_revision: Union[str, Sequence[str], None] = 'd7fa615cd804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unique_pending_invite'), table_name='organization_invites', postgresql_where="(status = 'PENDING'::invitestatus)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_unique_pending_invite'), 'organization_invites', ['organization_id', 'email'], unique=True, postgresql_where="(status = 'PENDING'::invitestatus)")
    # ### end Alembic commands ###
